version: '3'
services:
    postgis:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=geopostgis
        ports:
            - "5432:5432"
        volumes:
            - ${PATH_PREFIX}/db/data:/var/lib/postgresql/data


    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ${PATH_PREFIX}/db/mongo_data:/data/db



    jupyter:
        image: mrmaksimize/docker_geostack:latest
        restart: always
        volumes:
            - ${PATH_PREFIX}/working_dir:/home/jovyan/work
        depends_on:
            - postgres
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - POSTGRES_DB=geopostgis
        ports:
            - "8888:8888"
        links:
            - postgis:postgis
        command: start-notebook.sh

    adminer:
        image: adminer
        restart: always
        #HOST:CONTAINER
        ports:
            - "8082:8080"
        links:
            - postgis:postgis


    mongoexpress:
        image: mongo-express
        restart: always
        #HOST:CONTAINER
        ports:
            - "8081:8081"
        links:
            - mongo:mongo

