[webserver]
port = ":9090"              # port to bind the web server to. defaults ":8080"
CORSAllowedOrigin = "*"

# register data providers
[[providers]]
name = "osmtest"       # provider name is referenced from map layers (required)
type = "postgis"            # the type of data provider. currently only supports postgis (required)
host = "postgis"          # postgis database host (required)
port = 5432                 # postgis database port (required)
database = "geopostgis"         # postgis database name (required)
user = "airmaster"             # postgis database user (required)
password = "airmasterPass"               # postgis database password (required)
srid = 3857                 # The default srid for this provider. Defaults to WebMercator (3857) (optional)
max_connections = 50        # The max connections to maintain in the connection pool. Default is 100. (optional)


  [[providers.layers]]
  name = "road"
  geometry_fieldname = "way"
  id_fieldname = "osm_id"
  sql = "SELECT ST_AsBinary(way) AS way, osm_id FROM planet_osm_roads WHERE way && !BBOX!"

  [[providers.layers]]
  name = "bicycle"
  geometry_fieldname = "way"
  id_fieldname = "osm_id"
  sql = "SELECT ST_AsBinary(way) AS way, osm_id, bicycle FROM planet_osm_polygon WHERE bicycle is NOT NULL AND (way && !BBOX!)"

[[maps]]
name = "road_networks"

  [[maps.layers]]
  provider_layer = "osmtest.road"
  min_zoom = 8
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "osmtest.bicycle"
  min_zoom = 8
  max_zoom = 20



